// src/router/redirects.js

const redirects = [
    // Privacy Policy Redirects
    { from: "/privacy", to: "/privacy-policy" },
    { from: "/policy", to: "/privacy-policy" },
    { from: "/privacypolicy", to: "/privacy-policy" },
    { from: "/policies", to: "/privacy-policy" },
  
    // Terms and Conditions Redirects
    { from: "/terms", to: "/terms-and-conditions" },
    { from: "/conditions", to: "/terms-and-conditions" },
    { from: "/t&c", to: "/terms-and-conditions" },
    { from: "/tc", to: "/terms-and-conditions" },
    { from: "/termsconditions", to: "/terms-and-conditions" },
    { from: "/term", to: "/terms-and-conditions" },
    { from: "/condition", to: "/terms-and-conditions" },
    
      // About Page Redirects
  { from: "/about", to: "/about-us" },
  { from: "/aboutus", to: "/about-us" },
  { from: "/aboutme", to: "/about-us" },

  // Contact Page Redirects
  { from: "/contactus", to: "/contact-us" },
  { from: "/contact", to: "/contact-us" },
  { from: "/contactme", to: "/contact-us" },

  // FAQ Page Redirects
  { from: "/faqs", to: "/frequently-asked-questions" },
  { from: "/faq", to: "/frequently-asked-questions" },
  { from: "/frequent-asked-questions", to: "/frequently-asked-questions" },
  { from: "/facts", to: "/frequently-asked-questions" },

  // Help Page Redirects
  { from: "/help-us", to: "/help" },
  { from: "/helpus", to: "/help" },
  { from: "/helpme", to: "/help" },
  { from: "/help-me", to: "/help" },
  { from: "/need-help", to: "/help" },
  { from: "/needhelp", to: "/help" },

  { from: "/dashboard", to: "/account/dashboard" },
  { from: "/mydashboard", to: "/account/dashboard" },
  { from: "/my-dashboard", to: "/account/dashboard" },
  { from: "/account", to: "/account/dashboard" },
  { from: "/myaccount", to: "/account/dashboard" },
  { from: "/my-account", to: "/account/dashboard" },
  { from: "/account/mydashboard", to: "/account/dashboard" },
  { from: "/account/my-dashboard", to: "/account/dashboard" },
  { from: "/account/account", to: "/account/dashboard" },
  { from: "/account/myaccount", to: "/account/dashboard" },
  { from: "/account/my-account", to: "/account/dashboard" },
  { from: "/login", to: "/account/login" },
  { from: "/log-in", to: "/account/login" },
  { from: "/sign-in", to: "/account/login" },
  { from: "/signin", to: "/account/login" },
  { from: "/account/log-in", to: "/account/login" },
  { from: "/account/sign-in", to: "/account/login" },
  { from: "/account/signin", to: "/account/login" },
  { from: "/orders", to: "/account/orders" },
  { from: "/myorders", to: "/account/orders" },
  { from: "/my-orders", to: "/account/orders" },
  { from: "/account/myorders", to: "/account/orders" },
  { from: "/account/my-orders", to: "/account/orders" },
  { from: "/register", to: "/account/register" },
  { from: "/register-me", to: "/account/register" },
  { from: "/signup", to: "/account/register" },
  { from: "/sign-up", to: "/account/register" },
  { from: "/account/register-me", to: "/account/register" },
  { from: "/account/signup", to: "/account/register" },
  { from: "/account/sign-up", to: "/account/register" },
  { from: "/settings", to: "/account/settings" },
  { from: "/mysettings", to: "/account/settings" },
  { from: "/my-settings", to: "/account/settings" },
  { from: "/setting", to: "/account/settings" },
  { from: "/mysetting", to: "/account/settings" },
  { from: "/my-setting", to: "/account/settings" },
  { from: "/options", to: "/account/settings" },
  { from: "/myoptions", to: "/account/settings" },
  { from: "/my-options", to: "/account/settings" },
  { from: "/option", to: "/account/settings" },
  { from: "/myoption", to: "/account/settings" },
  { from: "/my-option", to: "/account/settings" },
  { from: "/account/mysettings", to: "/account/settings" },
  { from: "/account/my-settings", to: "/account/settings" },
  { from: "/account/setting", to: "/account/settings" },
  { from: "/account/mysetting", to: "/account/settings" },
  { from: "/account/my-setting", to: "/account/settings" },
  { from: "/account/options", to: "/account/settings" },
  { from: "/account/myoptions", to: "/account/settings" },
  { from: "/account/my-options", to: "/account/settings" },
  { from: "/account/option", to: "/account/settings" },
  { from: "/account/myoption", to: "/account/settings" },
  { from: "/account/my-option", to: "/account/settings" },
  { from: "/wishlist", to: "/account/wishlist" },
  { from: "/mywishlist", to: "/account/wishlist" },
  { from: "/my-wishlist", to: "/account/wishlist" },
  { from: "/account/mywishlist", to: "/account/wishlist" },
  { from: "/account/my-wishlist", to: "/account/wishlist" },

  { from: "/home", to: "/" },

  { from: "/purchaseconfirmation", to: "/order/confirmation" },
  { from: "/purchase-confirmation", to: "/order/confirmation" },
  { from: "/orderconfirmation", to: "/order/confirmation" },
  { from: "/order-confirmation", to: "/order/confirmation" },
  { from: "/track", to: "/order/track" },
  { from: "/tracking", to: "/order/track" },
  { from: "/trackorder", to: "/order/track" },
  { from: "/track-order", to: "/order/track" },

  { from: "/mycart", to: "/cart" },
  { from: "/my-cart", to: "/cart" },
  { from: "/shoppingcart", to: "/cart" },
  { from: "/shopping-cart", to: "/cart" },

  { from: "/check-out", to: "/checkout" },
  { from: "/pay", to: "/checkout" },
  { from: "/paynow", to: "/checkout" },
  { from: "/pay-now", to: "/checkout" },
  ];
  
  export default redirects;
  